export const metadata = {
  title: 'Rule Engine',
  description: 'Generated by Next.js',
}
import 'c/styles/globals.css'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
